### ISSUE TITLE
Where is the new update?

### ISSUE THREAD

**Issue by hullymoly** [WangDaYeeeeee/Mysplash#31]
I can't wait that. Because I really excited about new features. Please help.

**Comment by WangDaYeeeeee** [comment]
I've already sent a new update now....

**Comment by rugk** [comment]
FDroid still has v3.0.5. You've published [v3.0.6](https://github.com/WangDaYeeeeee/Mysplash/releases/tag/3.0.6) and already committed [v3.0.7](https://github.com/WangDaYeeeeee/Mysplash/commit/e0f31bdee84502233880c7b5aed9eaaad1790983) (but not released yet).

The built for [v3.0.6 is said to have failed](https://f-droid.org/wiki/page/com.wangdaye.mysplash#3.0.6), although [the built log claims otherwise](https://f-droid.org/wiki/page/com.wangdaye.mysplash/lastbuild_306#Build_Log).
Maybe with a new release you can easily fix this and trigger a re-built.

**Comment by WangDaYeeeeee** [comment]
@rugk 
Yeah I've already learned how to post updates and released a new version in GitHub ("3.0.6").

**Comment by rugk** [comment]
That's not what I was talking about. See:
> The built for v3.0.6 is said to have failed, although the built log claims otherwise.

So the last built failed on the FDroid server - for whatever reason. That's why FDroid users do not get it.

And still v3.0.7 has not been released yet.

**Comment by WangDaYeeeeee** [comment]
@rugk 

The build for v3.0.7 is in test, it's not a final version.
